/*
 * This source file was generated by the Gradle 'init' task
 */
package javaptit1.projjava;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void testPlaceholder() {
        // Placeholder test - add your actual tests here
        assertTrue(true, "Placeholder test");
    }
}
